---
sudo: required

env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: centos
      VERSION: 8
    - DISTRIBUTION: oraclelinux
      VERSION: 7
    - DISTRIBUTION: oraclelinux
      VERSION: 8
    - DISTRIBUTION: ubuntu
      VERSION: 16.04
    - DISTRIBUTION: ubuntu
      VERSION: 18.04
    - DISTRIBUTION: debian
      VERSION: 9
# Debian buster docker image is buggy
#    - DISTRIBUTION: debian
#      VERSION: 10
services:
  - docker

before_install:
  # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  # Allow fetching other branches than master
  #- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  # Fetch the branch with test code
  #- git fetch origin docker-tests
  #- git worktree add docker-tests origin/docker-tests

script:
  - ROLE=msaf1980.squid ./tests/docker-tests.sh
