# tasks file for squid

- import_tasks: redhat.yml
  when:
    - ansible_os_family|lower in ('centos', 'redhat')

- import_tasks: debian.yml
  when:
    - ansible_os_family|lower == 'debian'

- name: Backup squid config
  become: yes
  shell: tar -czf {{ squid_config_dir }}.tar.gz {{ squid_config_dir }}
  changed_when: False
  tags:
    - squid

- name: Create Squid configuration file
  become: yes
  template:
    src: squid.conf.j2
    dest: "{{ squid_config_dir }}/squid.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload squid
  tags:
    - squid

- name: Ensure Squid service is started and enabled on boot
  become: yes
  service:
    name: "{{ squid_service_name }}"
    state: started
    enabled: yes
  tags:
    - squid

- name: Check squid config
  become: yes
  shell: "{{ squid_bin }} -k check"
  changed_when: False
  tags:
    - squid

