---
# handlers file for squid

- name: restart squid
  service:
    name: "{{ squid_service_name }}"
    state: restarted
#  notify: check squid
  tags:
    - squid

- name: reload squid
  service:
    name: "{{ squid_service_name }}"
    state: reloaded
#  notify: check squid
  tags:
    - squid

#- name: check squid
#  shell: service {{ squid_service_name }} status
#  changed_when: False
